diaAbertoConf/urls.py
from django.urls import path

from . import views


app_name =  'diaAbertoConf'
urlpatterns = [
    path('', views.index, name='index'),
    path('DiaAbertoConf/', views.editConfDiaAberto, name='editConfig'),
    
    path('Transportes/', views.showTransportes, name='allTransportes'),
    path('Transportes/create', views.createTransporte, name='createTransporte'),
    path('Transportes/delete/<int:id>', views.deleteTransporte, name= 'deleteTransporte'),
    path('Transportes/update/<int:id>', views.updateTransporte, name='updateTransporte'),

    path('Transportes/HorariosTransporte/', views.showHorarios_Transporte, name='allHorarios'),
    path('Transportes/HorariosTransporte/create', views.createHorario_Transporte, name='createHorarioTransporte'),
    path('Transportes/HorariosTransporte/delete/<int:id>', views.deleteHorario_Transporte, name= 'deleteHorarioTransporte'),
    path('Transportes/HorariosTransporte/update/<int:id>', views.updateHorario_Transporte, name='updateHorarioTransporte'),

    path('Transportes/<int:id>/InscriçãoAssociada/', views.showInscAssociada, name= 'showInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/create', views.createInscAssociada, name= 'createInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/update/<int:idRota_Insc>', views.updateInscAssociada, name='updateInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/delete/<int:idRota_Insc>', views.deleteInscAssociada, name= 'deleteInscAssociadas'),


    path('GestaoEmentas/',views.gestaoEmentas, name='gestaoEmentas'),
    path('GestaoEmentas/delete/<int:id>',views.deleteEmenta, name='deleteEmenta'),
    path('GestaoEmentas/create',views.createEmenta, name='createEmenta'),
    path('GestaoEmentas/update/<int:id>', views.EditarEmenta, name='EditarEmenta'),
    

]   

tarefas/urls.py
from django.urls import path
from . import views


app_name =  'tarefas'
urlpatterns = [
    path('',views.showTarefas, name='showTarefas'),
    path('create', views.createTarefa, name='createTarefa'),
    path('delete/<int:id>', views.deleteTarefa, name= 'deleteTarefa'),
    path('atribuirColab/<int:id>', views.atribuirTarefa, name='atribuirTarefa'),
    path('update/<int:id>', views.updateTarefa, name= 'updateTarefa'),
    path('removerColab/<int:id>/<int:colabid>', views.removeColab, name='removeColaborador'),

    path('getSessoes/<int:atividadeid>', views.getSessoes, name='getSessoes'),
    path('getSessoesByDate/<str:date>', views.getSessoesBydate, name='getSessoesByDate'),
    path('getSessoesNext/<int:sessao_atividadeid>/<str:date>', views.getSessoesNext, name='getSessoesNext'),
    path('getHoraFim/<int:sessao_atividadeid>', views.getHoraFim, name='getHoraFim'),
    path('getLocal_Sessao/<int:sessao_atividadeid>', views.getLocal_Sessao, name='getLocal_Sessao'),
    path('getGrupos/<int:sessao_atividade_origem>/<int:sessao_atividade_destino>/<str:dia>', views.getGrupos, name='getGrupos'),
    
]

ualgDiaAberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('diaAbertoConf.urls')),
    path('GestaoAtividades/', include('atividades.urls')),
    path('Tarefas/', include('tarefas.urls')),
    path('Utilizador/', include('utilizadores.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

tarefas/models.py
from django.db import models

# Create your models here.

class Tarefa(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    sessao_atividadeid_destino = models.ForeignKey("atividades.SessaoAtividade", related_name='destino', on_delete=models.SET_NULL, db_column='Sessao_AtividadeID_Destino', blank=True, null=True)  # Field name made lowercase.
    sessao_atividadeid_origem = models.ForeignKey("atividades.SessaoAtividade", related_name='origem', on_delete=models.SET_NULL, db_column='Sessao_AtividadeID_Origem', blank=True, null=True)  # Field name made lowercase.
    sessao_atividadeid = models.ForeignKey("atividades.SessaoAtividade", related_name='TarefaSessaoAtividade', on_delete=models.CASCADE, db_column='SessaoAtividadeID', blank=True, null=True)
    utilizadorid = models.ForeignKey("utilizadores.Utilizador", related_name='tarefa_coordenador', on_delete=models.DO_NOTHING, db_column='UtilizadorID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    tipoTarefa = models.CharField(db_column='TipoTarefa', max_length=255, blank=True, null=True)  # Field name made lowercase.
    origem = models.CharField(db_column='Origem', max_length=255, blank=True, null=True)  # Field name made lowercase.
    destino = models.CharField(db_column='Destino', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horario = models.TimeField(db_column='Horario', blank=True, null=True)  # Field name made lowercase.
    data = models.DateField(db_column='Data', blank=True, null=True)
    estado = models.BooleanField(db_column='Estado', blank=True, null=True)
    colaboradores = models.ManyToManyField("utilizadores.Utilizador", related_name='tarefa_colaborador')

    class Meta:
        db_table = 'tarefa'
        permissions = [
            ("assign_tarefa", "Can assign a tarefa to a colaborador "),
            ("remove_colab_from_tarefa", "Can remove a colaborador from a tarefa"),
        ]


class InscricaoTarefa(models.Model):
    inscricaoid = models.ForeignKey("atividades.Inscricao", on_delete=models.CASCADE, db_column='InscricaoID', blank=True, null=True)
    tarefaid = models.ForeignKey(Tarefa, on_delete=models.CASCADE, db_column='TarefaID', blank=True, null=True)

    class Meta:
        db_table = 'inscricao_tarefa'

tarefas/views.py
import datetime, json

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.forms import formset_factory
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required, permission_required

from tarefas.filters import TarefaFilter, ColaboradorFilter
from tarefas.models import Tarefa, InscricaoTarefa
from diaAbertoConf.models import DiaAberto
from atividades.models import UnidadeOrganica, SessaoAtividade, Inscricao, SessaoAtividadeInscricao
from utilizadores.models import Utilizador
from tarefas.forms import TarefaForm, TarefaAtividadeForm, TarefaTransporteForm, TarefaGruposForm, TarefaGruposFormset


# Create your views here.

# ---------------------------------------------------------
# Tarefas CRUD- Create Read Update Delete
# ----------------------------------------------------------

@login_required()
@permission_required('tarefas.add_tarefa', raise_exception=True)
def createTarefa(request):

    saved = False
    user = request.user
    
    if request.method == 'POST':
        formTarefa = TarefaForm(request.POST)

        if formTarefa.is_valid():
            tipoTarefa = formTarefa.cleaned_data['tipoTarefa']
            
            if tipoTarefa == 'Atividade':
                formTarefaAtividade = TarefaAtividadeForm(request.POST, uoId=user.unidade_organicaid)
                if formTarefaAtividade.is_valid():
                    t = formTarefa.save(commit=False)
                    t.estado = False
                    # Change for logged in user
                    t.utilizadorid = user
                    t.sessao_atividadeid = SessaoAtividade.objects.get(id=formTarefaAtividade.cleaned_data['sessaoAtividade'])
                    t.horario = t.sessao_atividadeid.sessaoid.hora_de_inicio
                    t.data = t.sessao_atividadeid.data
                    t.save()
                    saved = True
            elif tipoTarefa == 'Transporte':
                formTarefaTransporte = TarefaTransporteForm(request.POST)
                formSetTarefaGrupos = TarefaGruposFormset(request.POST)
                if formTarefaTransporte.is_valid() and formSetTarefaGrupos.is_valid():
                    t = formTarefa.save(commit=False)
                    t.estado = False
                    # Change for logged in user
                    t.utilizadorid = user
                    t.sessao_atividadeid_destino = SessaoAtividade.objects.get(
                        id=formTarefaTransporte.cleaned_data['sessaoAtividade_destino'])
                    t.sessao_atividadeid_origem = SessaoAtividade.objects.get(
                        id=formTarefaTransporte.cleaned_data['sessaoAtividade_origem'])
                    t.origem = formTarefaTransporte.cleaned_data['origem']
                    t.destino = formTarefaTransporte.cleaned_data['destino']
                    t.horario = formTarefaTransporte.cleaned_data['horario']
                    t.data = formTarefaTransporte.cleaned_data['dia']

                    t.save()
           
                    for form in formSetTarefaGrupos:
                        InscTarefa = InscricaoTarefa(inscricaoid=Inscricao.objects.get(id=form.cleaned_data['inscricao']),tarefaid=t)
                        InscTarefa.save()

                    saved = True

    formTarefa = TarefaForm()
    # Change later so that id equals the UO of the autheticated Coordenador
    formTarefaAtividade = TarefaAtividadeForm(request.GET or None, uoId=user.unidade_organicaid)
    formTarefaTransporte = TarefaTransporteForm(request.GET or None)
    formSetTarefaGrupos = TarefaGruposFormset(request.GET or None)
    

    context = {'formTarefa': formTarefa,
               'formTarefaAtividade': formTarefaAtividade,
               'formTarefaTransporte': formTarefaTransporte,
               'formSetTarefaGrupos': formSetTarefaGrupos,
               'saved': saved,
               }

    return render(request, 'tarefas/AdicionarTarefa.html', context)

@login_required()
@permission_required('tarefas.view_tarefa', raise_exception=True)
def showTarefas(request):

    user = request.user

    #Filtering Results
    if user.user_type == 0b10000:
        tarefasFiltered = TarefaFilter(request.GET, queryset=Tarefa.objects.all())
    else:
        tarefasFiltered = TarefaFilter(request.GET, queryset=Tarefa.objects.filter(utilizadorid = user))

    #Ordering Results
    order_by = request.GET.get('order_by')
    direction = request.GET.get('direction')
    if order_by:
        ordering = Lower(order_by)
        if direction == 'desc':
            ordering = '-{}'.format(order_by)
        allTarefas = tarefasFiltered.qs.order_by(ordering)
    else:
        allTarefas = tarefasFiltered.qs


    paginator = Paginator(allTarefas, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    allTarefaGrupos = {}
    allTarefaColaboradores = {}

    #Gets all grupos and colaboradores that are in the tarefas of page_obj
    for tarefa in page_obj:
        insc = InscricaoTarefa.objects.filter(tarefaid = tarefa.id)
        if insc:
            allTarefaGrupos[tarefa.id] = insc
        
        colab = tarefa.colaboradores.all()
        if colab:
            allTarefaColaboradores[tarefa.id] = colab

    #Gets all the dates of the diaAberto
    daysDiaAberto = []
    try:           
        diaAberto = DiaAberto.objects.all()[0]
        start_date = diaAberto.data_inicio
        end_date = diaAberto.data_fim
        current_date = start_date
        daysDiaAberto.append(start_date)
        while current_date <  end_date:
            current_date += datetime.timedelta(days=1)
            daysDiaAberto.append(current_date)
    except IndexError:
        pass
    
    context = { 'page_obj': page_obj,
                'order_by': order_by,
                'direction': direction,
                'allTarefaGrupos': allTarefaGrupos,
                'allTarefaColaboradores': allTarefaColaboradores,
                'nomeTarefaSearched': request.GET.get('nome'),
                'tipoTarefaSearched': request.GET.get('tipoTarefa'),
                'estadoTarefaSearched': request.GET.get('estado'),
                'dataTarefaSearched': request.GET.get('data'),
                'horario_gte_Searched': request.GET.get('horario_gte'),
                'horario_lte_Searched': request.GET.get('horario_lte'),
                'nomeColaboradorSearched': request.GET.get('colaboradores__nome'),
                'emailColaboradorSearched': request.GET.get('colaboradores__email'),
                'datasDiaAberto': daysDiaAberto               
            }

    return render(request, 'tarefas/showTarefas.html', context)

@login_required()
@permission_required('tarefas.assign_tarefa', raise_exception=True)
def atribuirTarefa(request, id):
    tarefa = Tarefa.objects.get(id=id)
    uo_id = tarefa.utilizadorid.unidade_organicaid
    resultColaboradores = []

    if request.method == 'POST':
        colabid = request.POST.get('utilizadorid')
        tarefa.colaboradores.add(Utilizador.objects.get(id= colabid))
        tarefa.estado = True
        tarefa.save()
        return redirect('tarefas:showTarefas')


    # change later depending on other group user_type numeration
    allcolaboradores = Utilizador.objects.filter(unidade_organicaid=uo_id).filter(user_type=0b00010)

    colaboradoresFiltered = ColaboradorFilter(request.GET, allcolaboradores)

    #Ordering Results
    order_by = request.GET.get('order_by')
    direction = request.GET.get('direction')
    if order_by:
        ordering = Lower(order_by)
        if direction == 'desc':
            ordering = '-{}'.format(order_by)
        colaboradores = colaboradoresFiltered.qs.order_by(ordering)
    else:
        colaboradores = colaboradoresFiltered.qs

    #Check if the colaboradores are busy
    for colab in colaboradores:
        busy = False
        for colabTarefa in colab.tarefa_colaborador.all():
            if (colabTarefa.horario == tarefa.horario and colabTarefa.data == tarefa.data):
                busy = True
                break
        if not busy:
            resultColaboradores.append(colab)

    paginator = Paginator(resultColaboradores, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    tarefaGrupos = None
    if tarefa.tipoTarefa == 'Transporte':
        tarefaGrupos = InscricaoTarefa.objects.filter(tarefaid=tarefa.id)

    context = {
        'page_obj': page_obj,
        'order_by': order_by,
        'direction': direction,
        'colaboradores': resultColaboradores,
        'dadosTarefa': tarefa,
        'dadosTarefaGrupos': tarefaGrupos,
        'nomeColaboradorSearched': request.GET.get('nomeColab'),
        'emailColaboradorSearched': request.GET.get('emailColab'),
    }
    return render(request, 'tarefas/AtribuirTarefa.html', context)

@login_required()
@permission_required('tarefas.remove_colab_from_tarefa', raise_exception=True)
def removeColab(request, id, colabid):
    tarefa = Tarefa.objects.get(id=id)
    tarefa.colaboradores.remove(Utilizador.objects.get(id=colabid))

    if not tarefa.colaboradores.all():
        tarefa.estado = False
        tarefa.save()
    
    return redirect('tarefas:showTarefas')

@login_required()
@permission_required('tarefas.delete_tarefa', raise_exception=True)
def deleteTarefa(request, id):
    tarefa = Tarefa.objects.get(id=id)
    tarefa.delete()
    return redirect('tarefas:showTarefas')

@login_required()
@permission_required('tarefas.change_tarefa', raise_exception=True)
def updateTarefa(request, id):
    user = request.user

    dados_Tarefa = Tarefa.objects.get(id=id)
    formTarefaTransporte = None
    formSetTarefaGrupos = None
    formTarefaAtividade = None

    if request.method == "GET":
        formTarefa = TarefaForm(instance=dados_Tarefa)
        
        if dados_Tarefa.tipoTarefa == 'Transporte':
            

tarefas/templates/tarefas/AdicionarTarefa.html
{% extends "tarefas/showTarefas.html" %}

	{% block content %}
    	<div class="mt-3 mx-2 mb-5 pb-5">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb bg-white">
					<li class="breadcrumb-item"><a href="{% url 'diaAbertoConf:index' %}">Início</a></li>
					<li class="breadcrumb-item"><a href="{% url 'tarefas:showTarefas' %}">Tarefas</a></li>
					<li class="breadcrumb-item active">Adicionar tarefa</li>
				</ol>
			</nav>
    	    <div class = "row">
    		    <div class = "col-sm-4 offset-sm-4">
                    <h4 style="text-align:center;">Adicionar tarefa</h4>
    		    </div>
				<div class = "col-sm-4 offset-sm-4">
    		    {% if saved %}
                    <div class="alert alert-primary" role="alert" style="text-align:center;">
                        A Tarefa foi guardado com sucesso!
                    </div>
                {% endif %}
            	</div>
            </div>
    	    <hr class="mx-5">
    	    <div class = "row">
    		    <div class = "col-sm-6  offset-sm-3 mt-5">
					<form action = "{% url 'tarefas:createTarefa' %}" method="post">
						{% csrf_token %}
						<div class="form-group row">
    						<label class="form-check-label col-sm-3"> {{formTarefa.nome.label}} </label>
    						<div class="col-sm-8">
                                {{formTarefa.nome}}
    						</div>
  						</div>
  						<div class="form-group row">
    						<label class="form-check-label col-sm-3"> {{formTarefa.descricao.label}} </label>
    						<div class="col-sm-8">
                                {{formTarefa.descricao}}
    						</div>
  						</div>
  						<div class="form-group row pb-5">
                            <label class="col-sm-3"> {{formTarefa.tipoTarefa.label}} </label>
    						<div class="col-sm-8 ">
                                {{formTarefa.tipoTarefa}}
    						</div>
  						</div>
                        <hr>
						<div class="TarefaAtividade" style="display:none">
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaAtividade.atividade.label}} </label>
    							<div class="col-sm-8">
                        	        {{formTarefaAtividade.atividade}}
    							</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaAtividade.sessaoAtividade.label}} </label>
    							<div class="col-sm-8">
                        	        {{formTarefaAtividade.sessaoAtividade}}
    							</div>
  							</div>
							<hr>
						</div>
						<div class="TarefaTransporte" style="display:none">
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.dia.label}} </label>
    							<div class="col-sm-8">
									{{formTarefaTransporte.dia}}
    							</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.sessaoAtividade_origem.label}} </label>
    							<div class="col-sm-8">
                        	        {{formTarefaTransporte.sessaoAtividade_origem}}
    							</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.origem.label}} </label>
    							<div class="col-sm-8">
									<input type="text" name="origem" class="form-control" id="id_origem">    							
								</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.sessaoAtividade_destino.label}} </label>
    							<div class="col-sm-8">
                        	        {{formTarefaTransporte.sessaoAtividade_destino}}
    							</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.destino.label}} </label>
    							<div class="col-sm-8">
									<input type="text" name="destino" class="form-control" id="id_destino">    							
								</div>
  							</div>
							<div class="form-group row">
                        	    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.horario.label}} </label>
    							<div class="col-sm-8">
						      		<input id="horario" type="time" name="horario" class="form-control">
    							</div>
  							</div>
							{{formSetTarefaGrupos.management_form}}
							{% for grupo in formSetTarefaGrupos %}
							<div class="tarefaGrupo-form-comp">
								<hr>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{grupo.inscricao.label}} </label>
    								<div class="col-sm-8">
                        		        {{grupo.inscricao}}
    								</div>
  								</div>
								<div class="form-group row">
									<div class="col-sm-10">
										<button class="remove-form-row btn btn-outline-danger mr-3">Remover Grupo</button>
										<button class="add-form-row btn btn-outline-success">Adicionar Grupo</button>
									</div>								
								</div>
							</div>
							{% endfor %}
							<hr>
						</div>
						<div class="form-group row mt-5">
							<div class="col-sm-10">
								<a type="button" class="btn btn-secondary mr-3" href="{% url 'tarefas:showTarefas' %}">Cancelar</a>
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
						</div>
					</form>
    		    </div>
    	    </div>
    	</div>
	{% endblock %}

	{% block js %}
	{% load static %}
			<script src={% static "tarefas/AdicionarTarefa.js" %}></script>
	{% endblock %}

tarefas/templates/tarefas/EditTarefa.html
{% extends "tarefas/showTarefas.html" %}

	{% block content %}
    	<div class="mt-3 mx-2 mb-5 pb-5">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb bg-white">
					<li class="breadcrumb-item"><a href="{% url 'diaAbertoConf:index' %}">Início</a></li>
					<li class="breadcrumb-item"><a href="{% url 'tarefas:showTarefas' %}">Tarefas</a></li>
					<li class="breadcrumb-item active">Editar tarefa</li>
				</ol>
			</nav>
    	    <div class = "row">
    		    <div class = "col-sm-4 offset-sm-4">
                    <h4 style="text-align:center;">Editar tarefa</h4>
    		    </div>
            </div>
    	    <hr class="mx-5">
    	    <div class = "row">
    		    <div class = "col-sm-6  offset-sm-3 mt-5">
					<form action = "{% url 'tarefas:updateTarefa' id=tarefa.id%}" method="post">
						{% csrf_token %}
						<div class="form-group row">
    						<label class="form-check-label col-sm-3"> {{formTarefa.nome.label}} </label>
    						<div class="col-sm-8">
                                {{formTarefa.nome}}
    						</div>
  						</div>
  						<div class="form-group row">
    						<label class="form-check-label col-sm-3"> {{formTarefa.descricao.label}} </label>
    						<div class="col-sm-8">
                                {{formTarefa.descricao}}
    						</div>
  						</div>
                        <hr>
                        {% if tarefa.tipoTarefa == 'Atividade' %}
							<div class="TarefaAtividade">
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaAtividade.atividade.label}} </label>
    								<div class="col-sm-8">
                        		        {{formTarefaAtividade.atividade}}
    								</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaAtividade.sessaoAtividade.label}} </label>
    								<div class="col-sm-8">
                        		        {{formTarefaAtividade.sessaoAtividade}}
    								</div>
  								</div>
							</div>
                        {% elif tarefa.tipoTarefa == 'Transporte' %}
							<div class="TarefaTransporte">
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.dia.label}} </label>
    								<div class="col-sm-8">
                        		       {{formTarefaTransporte.dia}}
    								</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.sessaoAtividade_origem.label}} </label>
    								<div class="col-sm-8">
                        		        {{formTarefaTransporte.sessaoAtividade_origem}}
    								</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.origem.label}} </label>
    								<div class="col-sm-8">
										<input type="text" name="origem" class="form-control" id="id_origem" value="{{formTarefaTransporte.origem.value}}">    							
									</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.sessaoAtividade_destino.label}} </label>
    								<div class="col-sm-8">
                        		        {{formTarefaTransporte.sessaoAtividade_destino}}
    								</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.destino.label}} </label>
    								<div class="col-sm-8">
										<input type="text" name="destino" class="form-control" id="id_destino" value="{{formTarefaTransporte.destino.value}}">    							
									</div>
  								</div>
								<div class="form-group row">
                        		    <label class="form-check-label col-sm-3"> {{formTarefaTransporte.horario.label}} </label>
    								<div class="col-sm-8">
						    	  		<input id="horario" type="time" name="horario" class="form-control" value={{formTarefaTransporte.horario.value|time:"H:i"}}>
    								</div>
  								</div>
								{{formSetTarefaGrupos.management_form}}
								{% for grupo in formSetTarefaGrupos %}
								<div class="tarefaGrupo-form-comp">
									<hr>
									<div class="form-group row">
                        			    <label class="form-check-label col-sm-3"> {{grupo.inscricao.label}} </label>
    									<div class="col-sm-8">
                        			        {{grupo.inscricao}}
    									</div>
  									</div>
									<div class="form-group row">
										<div class="col-sm-10">
											<button class="remove-form-row btn btn-outline-danger mr-3">Remover Grupo</button>
											<button class="add-form-row btn btn-outline-success">Adicionar Grupo</button>
										</div>								
									</div>
								</div>
								{% endfor %}
							</div>
                        {% endif %}
						<hr>
						<div class="form-group row mt-5">
							<div class="col-sm-10">
								<a type="button" class="btn btn-secondary mr-3" href="{% url 'tarefas:showTarefas' %}">Cancelar</a>
								<a class="btn btn-primary" href="" data-toggle="modal" data-target="#Modal">Editar</a>
							</div>
						</div>
						<div class="modal" id="Modal">
							<div class="modal-dialog">
								<div class="modal-content">
								    <!-- Modal Header -->
										<div class="modal-header">
											<h4 class="modal-title">Aviso</h4>
											<button type="button" class="close" data-dismiss="modal">×</button>
										</div>
										<!-- Modal body -->
										<div class="modal-body">
											<p>Tem a certeza que pretende guardar as alterações?</p>
                                            <p>A tarefa passará ao estado de 'Não Atribuída'</p>
										</div>
										<!-- Modal footer -->
										<div class="modal-footer">
											<button type="submit" class="btn btn-success" >Sim</button>
											<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
										</div>
                                </div>   
                            </div>     
						</div>
					</form>
    		    </div>
    	    </div>
    	</div>
	{% endblock %}
	{% block js %}
	{% load static %}
			<script src={% static "tarefas/AdicionarTarefa.js" %}></script>
	{% endblock %}