atividades/urls.py
from django.urls import path

from . import views


app_name =  'atividades'
urlpatterns = [
    
    path('Atividades/', views.showAtividades, name='allAtividades'),
    path('Atividades/<int:id>', views.showDetailsAtividade, name='showDetailsAtividade'),
    path('Atividades/create', views.createAtividade, name='createAtividade'),
    path('Atividades/delete/<int:id>', views.deleteAtividade, name='deleteAtividade'),
    path('Atividades/update/<int:id>', views.updateAtividade, name='updateAtividade'),
    path('Atividades/recuse/<int:id>', views.recuseAtividade, name='recuseAtividade'),
    path('Atividades/atribuir/<int:id>', views.atribuirLocal, name='atribuirLocal'),
    path('Atividades/changeAtribuir/<int:id>', views.updateAtribuirLocal, name='updateAtribuirLocal'),
    
    path('getEdificio/<int:campusid>', views.getEdificio, name='getEdificio'),
    path('getEdificioCampus/<int:campusid>', views.getEdificioCampus, name='getEdificioCampus'),
    path('getLocal/<int:edificioid>', views.getLocal, name='getLocal'),
    path('getLocalExterior/<int:campusid>', views.getLocalExterior, name='getLocalExterior'),
    path('getDescricaoLocal/<int:localid>', views.getDescricaoLocal, name='getDescricaoLocal'),
    path('getLocalImage/<int:localid>', views.getLocalImage, name='getLocalImage'),

    
    path('Edificios/', views.showEdificios, name='allEdificios'),
    path('Edificios/create', views.createEdificio, name='createEdificio'),
    path('Edificios/delete/<int:id>', views.deleteEdificio, name='deleteEdificio'),
    path('Edificios/update/<int:id>', views.updateEdificio, name='updateEdificio'),

    path('Campus/', views.showCampus, name='allCampus'),
    path('Campus/create', views.createCampus, name='addCampus'),
    path('Campus/delete/<int:id>', views.deleteCampus, name='deleteCampus'),
    path('Campus/update/<int:id>', views.updateCampus, name='updateCampus'),

    path('UnidadeOrganicas/', views.showUnidadeOrganicas, name='allUnidadeOrganicas'),
    path('UnidadeOrganicas/create', views.createUnidadeOrganica, name='createUnidadeOrganica'),
    path('UnidadeOrganicas/delete/<int:id>', views.deleteUnidadeOrganica, name='deleteUnidadeOrganica'),
    path('UnidadeOrganicas/update/<int:id>', views.updateUnidadeOrganica, name='updateUnidadeOrganica'),

    path('Departamentos/', views.showDepartamentos, name='allDepartamentos'),
    path('Departamentos/create', views.createDepartamento, name='createDepartamento'),
    path('Departamentos/delete/<int:id>', views.deleteDepartamento, name='deleteDepartamento'),
    path('Departamentos/update/<int:id>', views.updateDepartamento, name='updateDepartamento'),

    path('Locais/', views.showLocais, name='allLocais'),
    path('Locais/create', views.createLocal, name='addLocal'),
    path('Locais/delete/<int:id>', views.deleteLocal, name='deleteLocal'),
    path('Locais/update/<int:id>', views.updateLocal, name='updateLocal'),

    path('Tematicas', views.showTematicas, name='allTematicas'),
    path('Tematicas/create', views.addTematica, name='addTematica'),
    path('Tematicas/delete/<int:id>', views.deleteTematica, name='deleteTematica'),
    path('Tematicas/update/<int:id>', views.updateTematica, name='updateTematica'),

    path('Materiais/', views.showMateriais, name='allMateriais'),
    path('Materiais/create', views.createMaterial, name='addMaterial'),
    path('Materiais/delete/<int:id>', views.deleteMaterial, name='deleteMaterial'),
    path('Materiais/update/<int:id>', views.updateMaterial, name='updateMaterial'),

    path('Sessoes', views.showSessoes, name='allSessoes'),
    path('Sessoes/create', views.addSessao, name='addSessao'),
    path('Sessoes/update/<int:id>', views.updateSessao, name='updateSessao'),
    path('Sessoes/delete/<int:id>', views.deleteSessao, name="deleteSessao")
  
]

diaAbertoConf/urls.py
from django.urls import path

from . import views


app_name =  'diaAbertoConf'
urlpatterns = [
    path('', views.index, name='index'),
    path('DiaAbertoConf/', views.editConfDiaAberto, name='editConfig'),
    
    path('Transportes/', views.showTransportes, name='allTransportes'),
    path('Transportes/create', views.createTransporte, name='createTransporte'),
    path('Transportes/delete/<int:id>', views.deleteTransporte, name= 'deleteTransporte'),
    path('Transportes/update/<int:id>', views.updateTransporte, name='updateTransporte'),

    path('Transportes/HorariosTransporte/', views.showHorarios_Transporte, name='allHorarios'),
    path('Transportes/HorariosTransporte/create', views.createHorario_Transporte, name='createHorarioTransporte'),
    path('Transportes/HorariosTransporte/delete/<int:id>', views.deleteHorario_Transporte, name= 'deleteHorarioTransporte'),
    path('Transportes/HorariosTransporte/update/<int:id>', views.updateHorario_Transporte, name='updateHorarioTransporte'),

    path('Transportes/<int:id>/InscriçãoAssociada/', views.showInscAssociada, name= 'showInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/create', views.createInscAssociada, name= 'createInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/update/<int:idRota_Insc>', views.updateInscAssociada, name='updateInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/delete/<int:idRota_Insc>', views.deleteInscAssociada, name= 'deleteInscAssociadas'),


    path('GestaoEmentas/',views.gestaoEmentas, name='gestaoEmentas'),
    path('GestaoEmentas/delete/<int:id>',views.deleteEmenta, name='deleteEmenta'),
    path('GestaoEmentas/create',views.createEmenta, name='createEmenta'),
    path('GestaoEmentas/update/<int:id>', views.EditarEmenta, name='EditarEmenta'),
    

]   

tarefas/urls.py
from django.urls import path
from . import views


app_name =  'tarefas'
urlpatterns = [
    path('',views.showTarefas, name='showTarefas'),
    path('create', views.createTarefa, name='createTarefa'),
    path('delete/<int:id>', views.deleteTarefa, name= 'deleteTarefa'),
    path('atribuirColab/<int:id>', views.atribuirTarefa, name='atribuirTarefa'),
    path('update/<int:id>', views.updateTarefa, name= 'updateTarefa'),
    path('removerColab/<int:id>/<int:colabid>', views.removeColab, name='removeColaborador'),

    path('getSessoes/<int:atividadeid>', views.getSessoes, name='getSessoes'),
    path('getSessoesByDate/<str:date>', views.getSessoesBydate, name='getSessoesByDate'),
    path('getSessoesNext/<int:sessao_atividadeid>/<str:date>', views.getSessoesNext, name='getSessoesNext'),
    path('getHoraFim/<int:sessao_atividadeid>', views.getHoraFim, name='getHoraFim'),
    path('getLocal_Sessao/<int:sessao_atividadeid>', views.getLocal_Sessao, name='getLocal_Sessao'),
    path('getGrupos/<int:sessao_atividade_origem>/<int:sessao_atividade_destino>/<str:dia>', views.getGrupos, name='getGrupos'),
    
]

ualgDiaAberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('diaAbertoConf.urls')),
    path('GestaoAtividades/', include('atividades.urls')),
    path('Tarefas/', include('tarefas.urls')),
    path('Utilizador/', include('utilizadores.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

atividades/models.py
import datetime
from django.db import models


# Create your models here.

class Campus(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    localizacao = models.CharField(db_column='Localizacao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    contacto = models.CharField(db_column='Contacto', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'campus' 

    def __str__(self):
        return str(self.nome)

class Edificio(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    num_edificio = models.IntegerField(db_column='Num_edificio', blank=True, null=True)  # Field name made lowercase.
    nome_edificio = models.CharField(db_column='Nome_edificio', max_length=255, blank=True, null=True)  # Field name made lowercase
    campusid = models.ForeignKey(Campus, on_delete = models.CASCADE, db_column='CampusID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'edicifio'

    def __str__(self):
        return self.nome_edificio

class UnidadeOrganica(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    #campusid = models.ForeignKey(Campus, on_delete = models.CASCADE, db_column='CampusID', blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'unidade_organica'

class Departamento(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    unidade_organicaid = models.ForeignKey('UnidadeOrganica', on_delete = models.CASCADE, db_column='Unidade_OrganicaID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'departamento'

class Local(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    edicifioid = models.ForeignKey(Edificio, on_delete = models.CASCADE, db_column='EdicifioID', blank=True, null=True)  # Field name made lowercase.
    andar = models.IntegerField(db_column='Andar', blank=True, null=True)  # Field name made lowercase.
    sala = models.CharField(db_column='Sala', blank=True, null=True, max_length=255)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    indoor = models.BooleanField(db_column='Indoor', blank=True, null=True)  # Field name made lowercase.
    campusid = models.ForeignKey(Campus, on_delete = models.CASCADE, db_column='CampusID', blank=True, null=True)  # Field name made lowercase.
    mapa_sala = models.ImageField(upload_to='mapas_salas', blank=True, null=True)
    nome_local_exterior = models.CharField(db_column='nome_local_exterior', blank=True, null=True, max_length=255)

    def __str__ (self):
        if self.indoor:
            return str(self.campusid.nome) + ", " + str(self.edicifioid.nome_edificio) + ", " + "Andar" + " " + str(self.andar) + ", " + "Sala" + " " + str(self.sala)
        return str(self.campusid.nome) + ", " + str(self.nome_local_exterior)

    class Meta:
        
        db_table = 'local'


""" class Utilizador(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    #inscricaoid = models.ForeignKey(Inscricao, models.DO_NOTHING, db_column='InscricaoID', blank=True, null=True)  # Field name made lowercase.
    unidade_organicaid = models.ForeignKey(UnidadeOrganica, on_delete = models.CASCADE, db_column='Unidade_OrganicaID', blank=True, null=True)  # Field name made lowercase.
    departamentoid = models.ForeignKey(Departamento, on_delete = models.CASCADE, db_column='DepartamentoID', blank=True, null=True)  # Field name made lowercase.
    #registo_horarioid = models.ForeignKey(RegistoHorario, models.DO_NOTHING, db_column='Registo_HorarioID', blank=True, null=True)  # Field name made lowercase.
    #gestao_perfilid = models.ForeignKey(GestaoPerfil, models.DO_NOTHING, db_column='Gestao_PerfilID', blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.DateField(db_column='Data_de_nascimento', blank=True, null=True)  # Field name made lowercase.
    numero_telemovel = models.IntegerField(db_column='Numero_telemovel', blank=True, null=True)  # Field name made lowercase.
    cartao_cidadao = models.IntegerField(db_column='Cartao_cidadao', blank=True, null=True)  # Field name made lowercase.
    deficiencias = models.CharField(db_column='Deficiencias', max_length=255, blank=True, null=True)  # Field name made lowercase.
    permitir_localizacao = models.IntegerField(db_column='Permitir_localizacao', blank=True, null=True)  # Field name made lowercase.
    utilizar_dados_pessoais = models.IntegerField(db_column='Utilizar_dados_pessoais', blank=True, null=True)  # Field name made lowercase.
    tema_do_website = models.IntegerField(db_column='Tema_do_website', blank=True, null=True)  # Field name made lowercase.
    user_type = models.IntegerField(db_column='User_type')  # Field name made lowercase.
    daltonico = models.IntegerField(db_column='Daltonico', blank=True, null=True)  # Field name made lowercase.
    validado = models.IntegerField(db_column='Validado')  # Field name made lowercase.
    check_in_state = models.IntegerField(db_column='Check_in_state', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'utilizador' """

class Atividade(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    localid = models.ForeignKey('Local', on_delete = models.DO_NOTHING, db_column='LocalID', blank=True, null=True)  # Field name made lowercase.
    utilizadorid = models.ForeignKey("utilizadores.Utilizador", default = "", on_delete = models.CASCADE, db_column='UtilizadorID', null=True)  # Field name made lowercase.
    unidadeorganicaid = models.ForeignKey('UnidadeOrganica', default = "", on_delete = models.CASCADE, db_column='UnidadeOrganicaID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    duracao = models.IntegerField(db_column='Duracao', blank=True, null=True)  # Field name made lowercase.
    limite_de_participantes = models.IntegerField(db_column='Limite_de_participantes', blank=True, null=True)  # Field name made lowercase.
    validada = models.IntegerField(db_column='Validada', blank=True, null=True)  # Field name made lowercase.
    tipo_atividade = models.CharField(db_column='Tipo_atividade', max_length=255, blank=True, null=True)  # Field name made lowercase.
    public_alvo = models.CharField(db_column='Public_alvo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    editavel = models.BooleanField(db_column='Editavel', blank=True, null=True)  # Field name made lowercase.
    num_colaboradores = models.IntegerField(db_column='Num_Colaboradores', blank=True, null=True)

    class Meta:
        
        db_table = 'atividade'
        permissions = [
            ("validates_atividade", "Can validate atividade"),
            ("atribuir_local", "Can atribuir local da atividade"),
            ("alterar_local", "Can alterar local da atividade")
            ]

class Material(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'material'

    def __str__ (self): 
        return str(self.nome)

class Tematica(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'tematica'

    def __str__ (self): 
        return str(self.nome)

class Sessao(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    hora_de_inicio = models.TimeField(db_column='Hora_de_inicio', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return self.hora_de_inicio.strftime("%I:%M")

    class Meta:
        
        db_table = 'sessao'

class AtividadeDepartamento(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    atividadeid = models.ForeignKey(Atividade, on_delete = models.CASCADE, db_column='AtividadeID')  # Field name made lowercase.
    departamentoid = models.ForeignKey('Departamento', on_delete = models.CASCADE, db_column='DepartamentoID')  # Field name made lowercase.

    class Meta:
        
        db_table = 'atividade_departamento'


class AtividadeMaterial(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    atividadeid = models.ForeignKey(Atividade, on_delete = models.CASCADE, db_column='AtividadeID')  # Field name made lowercase.

atividades/templates/atividades/AdicionarCampus.html
{% extends "atividades/ShowAtividades.html" %}

	{% block content %}
    	<div class="mt-3 mx-2 pb-5">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb bg-white">
					<li class="breadcrumb-item"><a href="{% url 'diaAbertoConf:index' %}">Início</a></li>
					<li class="breadcrumb-item"><a href="{% url 'atividades:allCampus' %}">Campus</a></li>
					<li class="breadcrumb-item active">Adicionar campus</li>
				</ol>
			</nav>
    	    <div class = "row">
    		    <div class = "col-sm-4 offset-sm-4">
                    <h4 style="text-align:center;">Adicionar campus</h4>
    		    </div>
    		    <div class = "col-sm-4 offset-sm-4">
    		    {% if saved %}
                    <div class="alert alert-primary" role="alert" style="text-align:center;">
                        O campus foi guardado com sucesso!
                    </div>
                {% endif %}

                {% for key, value in form.errors.items %}
                    {% for error in value %}
                        <div class="alert alert-danger" style="text-align:center;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}

            </div>
            </div>
			<hr class="mx-5">
    	    <div class = "row">
    		    <div class = "col-sm-6 offset-sm-3 mt-5">
					<form action = "{% url 'atividades:addCampus' %}" method="post">
						{% csrf_token %}
 						<div class="form-group row">
							<div class="col-sm-4 col-form-label">
    							<label for="nome">Nome</label>
							</div>
                            <div class="col-sm-8">
                                <input id="nome" type="text" name="nome" class="form-control" required>
                            </div>
  						</div>
  						<div class="form-group row">
							<div class="col-sm-4 col-form-label">
    							<label for="localizacao">Localizacao</label>
							</div>
    						<div class="col-sm-8">
      							<input id="localizacao" type="text" name="localizacao" class="form-control" required>
    						</div>
  						</div>
						<div class="form-group row mt-5">
							<div class="col-sm-10">
								<a type="button" class="btn btn-secondary mr-3" href="{% url 'atividades:allCampus' %}">Cancelar</a>
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
						</div>
					</form>
    		    </div>
    	    </div>
    	</div>

	{% endblock %}
	{% block js %}
    	<!-- Optional JavaScript -->
    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	
		
	{% endblock %}

atividades/templates/atividades/AdicionarEdificio.html
{% extends "atividades/ShowAtividades.html" %}

	{% block content %}
    	<div class="mt-3 mx-2 pb-5">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb bg-white">
					<li class="breadcrumb-item"><a href="{% url 'diaAbertoConf:index' %}">Início</a></li>
					<li class="breadcrumb-item"><a href="{% url 'atividades:allEdificios' %}">Edifícios</a></li>
					<li class="breadcrumb-item active">Adicionar Edifício</li>
				</ol>
			</nav>
    	    <div class = "row">
    		    <div class = "col-sm-4 offset-sm-4">
                    <h4 style="text-align:center;">Adicionar Edifício</h4>
    		    </div>
    		    <div class = "col-sm-4 offset-sm-4">
    		    {% if saved %}
                    <div class="alert alert-primary" role="alert" style="text-align:center;">
                        O edifício foi guardado com sucesso!
                    </div>
                {% endif %}

                {% for key, value in form.errors.items %}
                    {% for error in value %}
                        <div class="alert alert-danger" style="text-align:center;">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
            	</div>
            </div>
			<hr class="mx-5">
    	    <div class = "row">
    		    <div class = "col-sm-6 offset-sm-3 mt-5">
					<form action = "{% url 'atividades:createEdificio' %}" method="post">
						{% csrf_token %}
 						<div class="form-group row">
							<div class="col-sm-4 col-form-label">
    							<label for="campusid">Campus</label>
							</div>
    						<div class="col-sm-8">
								<select name="campusid" id="campusid" class = "form-control" required>
                                    {% for campus in allCampus %}
                                    <option value="{{campus.id}}">{{campus.nome}}</option>
                                    {% endfor %}
                                </select>
    						</div>
  						</div>
  						<div class="form-group row">
							<div class="col-sm-4 col-form-label">
    							<label for="nome">Nome</label>
							</div>
    						<div class="col-sm-8">
      							<input id="nome_edificio" type="text" name="nome_edificio" class="form-control" required>
    						</div>
  						</div>
  						<div class="form-group row">
							<div class="col-sm-4 col-form-label">
    							<label for="nome">Número</label>
							</div>
    						<div class="col-sm-8">
      							<input id="num_edificio" type="number" min="1" name="num_edificio" class="form-control" required>
    						</div>
  						</div>
						<div class="form-group row mt-5">
							<div class="col-sm-10">
								<a type="button" class="btn btn-secondary mr-3" href="{% url 'atividades:allEdificios' %}">Cancelar</a>
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
						</div>
					</form>
    		    </div>
    	    </div>
    	</div>

	{% endblock %}
	{% block js %}
    	<!-- Optional JavaScript -->
    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	
		
	{% endblock %}

atividades/templates/atividades/GestaoAtividades.html
<!doctype html>
<html lang="en">
    <head>

	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	    <title>Dia Aberto Ualg | Atividades</title>
    </head>
    <body>
    	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    	    <a class="navbar-brand" href="{% url 'atividades:index' %}">Atividades Dia Aberto Ualg</a>
    	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    		    <ul class="navbar-nav mr-auto">
    		        <li class="nav-item">
    			        <a class="nav-link" href="{% url 'atividades:gestaoAtividades' %}">Gestão de Atividades</a>
    		        </li>
    		    </ul>
    	    </div>
    	</nav>
    	<nav aria-label="breadcrumb">
    	    <ol class="breadcrumb">
    		    <li class="breadcrumb-item"><a href="#">Página Inicial</a></li>
    		    <li class="breadcrumb-item"><a href="{% url 'atividades:index' %}">Atividades Dia Aberto</a></li>
    		    <li class="breadcrumb-item active" aria-current="page">Gestão de Atividades</li>
    	    </ol>
    	</nav>

    	<p></p>
    

    	<div class="container">
    	    <div class = "row">
    		    <div class = "col-sm-6 ">
                    <h2>Gestão de Atividades</h2>
                    <hr>
    		    </div>
            </div>
    	    <div class = "row">
    		    <div class = "col-sm-8 ">
    		    	<ul class="list-group">
    		    		<li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:showatividades' %}">Atividades</a>
                            <a href="{% url 'atividades:adicionaratividade' %}">+ Adicionar</a>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allEdificios' %}">Edifícios</a>
                            <a href="{% url 'atividades:showCreateEdificio' saved=0 %}">+ Adicionar</a>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allLocais' %}">Locais</a>
                            <a href="{% url 'atividades:showCreateLocal' saved=0 %}">+ Adicionar</a>
                        </li>
    		    		<li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allCampus' %}">Campus</a>
                            <a href="{% url 'atividades:showCreateCampus' saved=0 %}">+ Adicionar</a>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allUnidadeOrganicas' %}">Unidade Orgânicas</a>
                            <a href="{% url 'atividades:showCreateUnidadeOrganica' saved=0 %}">+ Adicionar</a>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allDepartamentos' %}">Departamentos</a>
                            <a href="{% url 'atividades:showCreateDepartamento' saved=0 %}">+ Adicionar</a>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'atividades:allTematicas' %}">Temáticas</a>
                            <a href="{% url 'atividades:showCreateTematica' %}">+ Adicionar</a>
                        </li>
    		    	</ul>
    		    </div>
    	    </div>
    	</div>


    	<!-- Optional JavaScript -->
    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>