atividades/urls.py
from django.urls import path

from . import views


app_name =  'atividades'
urlpatterns = [
    
    path('Atividades/', views.showAtividades, name='allAtividades'),
    path('Atividades/<int:id>', views.showDetailsAtividade, name='showDetailsAtividade'),
    path('Atividades/create', views.createAtividade, name='createAtividade'),
    path('Atividades/delete/<int:id>', views.deleteAtividade, name='deleteAtividade'),
    path('Atividades/update/<int:id>', views.updateAtividade, name='updateAtividade'),
    path('Atividades/recuse/<int:id>', views.recuseAtividade, name='recuseAtividade'),
    path('Atividades/atribuir/<int:id>', views.atribuirLocal, name='atribuirLocal'),
    path('Atividades/changeAtribuir/<int:id>', views.updateAtribuirLocal, name='updateAtribuirLocal'),
    
    path('getEdificio/<int:campusid>', views.getEdificio, name='getEdificio'),
    path('getEdificioCampus/<int:campusid>', views.getEdificioCampus, name='getEdificioCampus'),
    path('getLocal/<int:edificioid>', views.getLocal, name='getLocal'),
    path('getLocalExterior/<int:campusid>', views.getLocalExterior, name='getLocalExterior'),
    path('getDescricaoLocal/<int:localid>', views.getDescricaoLocal, name='getDescricaoLocal'),
    path('getLocalImage/<int:localid>', views.getLocalImage, name='getLocalImage'),

    
    path('Edificios/', views.showEdificios, name='allEdificios'),
    path('Edificios/create', views.createEdificio, name='createEdificio'),
    path('Edificios/delete/<int:id>', views.deleteEdificio, name='deleteEdificio'),
    path('Edificios/update/<int:id>', views.updateEdificio, name='updateEdificio'),

    path('Campus/', views.showCampus, name='allCampus'),
    path('Campus/create', views.createCampus, name='addCampus'),
    path('Campus/delete/<int:id>', views.deleteCampus, name='deleteCampus'),
    path('Campus/update/<int:id>', views.updateCampus, name='updateCampus'),

    path('UnidadeOrganicas/', views.showUnidadeOrganicas, name='allUnidadeOrganicas'),
    path('UnidadeOrganicas/create', views.createUnidadeOrganica, name='createUnidadeOrganica'),
    path('UnidadeOrganicas/delete/<int:id>', views.deleteUnidadeOrganica, name='deleteUnidadeOrganica'),
    path('UnidadeOrganicas/update/<int:id>', views.updateUnidadeOrganica, name='updateUnidadeOrganica'),

    path('Departamentos/', views.showDepartamentos, name='allDepartamentos'),
    path('Departamentos/create', views.createDepartamento, name='createDepartamento'),
    path('Departamentos/delete/<int:id>', views.deleteDepartamento, name='deleteDepartamento'),
    path('Departamentos/update/<int:id>', views.updateDepartamento, name='updateDepartamento'),

    path('Locais/', views.showLocais, name='allLocais'),
    path('Locais/create', views.createLocal, name='addLocal'),
    path('Locais/delete/<int:id>', views.deleteLocal, name='deleteLocal'),
    path('Locais/update/<int:id>', views.updateLocal, name='updateLocal'),

    path('Tematicas', views.showTematicas, name='allTematicas'),
    path('Tematicas/create', views.addTematica, name='addTematica'),
    path('Tematicas/delete/<int:id>', views.deleteTematica, name='deleteTematica'),
    path('Tematicas/update/<int:id>', views.updateTematica, name='updateTematica'),

    path('Materiais/', views.showMateriais, name='allMateriais'),
    path('Materiais/create', views.createMaterial, name='addMaterial'),
    path('Materiais/delete/<int:id>', views.deleteMaterial, name='deleteMaterial'),
    path('Materiais/update/<int:id>', views.updateMaterial, name='updateMaterial'),

    path('Sessoes', views.showSessoes, name='allSessoes'),
    path('Sessoes/create', views.addSessao, name='addSessao'),
    path('Sessoes/update/<int:id>', views.updateSessao, name='updateSessao'),
    path('Sessoes/delete/<int:id>', views.deleteSessao, name="deleteSessao")
  
]

diaAbertoConf/urls.py
from django.urls import path

from . import views


app_name =  'diaAbertoConf'
urlpatterns = [
    path('', views.index, name='index'),
    path('DiaAbertoConf/', views.editConfDiaAberto, name='editConfig'),
    
    path('Transportes/', views.showTransportes, name='allTransportes'),
    path('Transportes/create', views.createTransporte, name='createTransporte'),
    path('Transportes/delete/<int:id>', views.deleteTransporte, name= 'deleteTransporte'),
    path('Transportes/update/<int:id>', views.updateTransporte, name='updateTransporte'),

    path('Transportes/HorariosTransporte/', views.showHorarios_Transporte, name='allHorarios'),
    path('Transportes/HorariosTransporte/create', views.createHorario_Transporte, name='createHorarioTransporte'),
    path('Transportes/HorariosTransporte/delete/<int:id>', views.deleteHorario_Transporte, name= 'deleteHorarioTransporte'),
    path('Transportes/HorariosTransporte/update/<int:id>', views.updateHorario_Transporte, name='updateHorarioTransporte'),

    path('Transportes/<int:id>/InscriçãoAssociada/', views.showInscAssociada, name= 'showInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/create', views.createInscAssociada, name= 'createInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/update/<int:idRota_Insc>', views.updateInscAssociada, name='updateInscAssociadas'),
    path('Transportes/<int:id>/InscriçãoAssociada/delete/<int:idRota_Insc>', views.deleteInscAssociada, name= 'deleteInscAssociadas'),


    path('GestaoEmentas/',views.gestaoEmentas, name='gestaoEmentas'),
    path('GestaoEmentas/delete/<int:id>',views.deleteEmenta, name='deleteEmenta'),
    path('GestaoEmentas/create',views.createEmenta, name='createEmenta'),
    path('GestaoEmentas/update/<int:id>', views.EditarEmenta, name='EditarEmenta'),
    

]   

tarefas/urls.py
from django.urls import path
from . import views


app_name =  'tarefas'
urlpatterns = [
    path('',views.showTarefas, name='showTarefas'),
    path('create', views.createTarefa, name='createTarefa'),
    path('delete/<int:id>', views.deleteTarefa, name= 'deleteTarefa'),
    path('atribuirColab/<int:id>', views.atribuirTarefa, name='atribuirTarefa'),
    path('update/<int:id>', views.updateTarefa, name= 'updateTarefa'),
    path('removerColab/<int:id>/<int:colabid>', views.removeColab, name='removeColaborador'),

    path('getSessoes/<int:atividadeid>', views.getSessoes, name='getSessoes'),
    path('getSessoesByDate/<str:date>', views.getSessoesBydate, name='getSessoesByDate'),
    path('getSessoesNext/<int:sessao_atividadeid>/<str:date>', views.getSessoesNext, name='getSessoesNext'),
    path('getHoraFim/<int:sessao_atividadeid>', views.getHoraFim, name='getHoraFim'),
    path('getLocal_Sessao/<int:sessao_atividadeid>', views.getLocal_Sessao, name='getLocal_Sessao'),
    path('getGrupos/<int:sessao_atividade_origem>/<int:sessao_atividade_destino>/<str:dia>', views.getGrupos, name='getGrupos'),
    
]

ualgDiaAberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('diaAbertoConf.urls')),
    path('GestaoAtividades/', include('atividades.urls')),
    path('Tarefas/', include('tarefas.urls')),
    path('Utilizador/', include('utilizadores.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

utilizadores/urls.py
from django.urls import path
from . import views


app_name =  'utilizadores'
urlpatterns = [

    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
]

diaAbertoConf/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Transporte(models.Model):
    tipo_transporte = models.CharField(db_column='Tipo_de_transporte', max_length=255, blank=True, null=True)  # Field name made lowercase.
    capacidade = models.IntegerField(db_column='Capacidade', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.tipo_transporte)

    class Meta:
        
        db_table = 'transporte'

class HorarioTransporte(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    hora_de_partida = models.TimeField(db_column='Hora_de_partida', blank=True, null=True)  # Field name made lowercase.
    hora_de_chegada = models.TimeField(db_column='Hora_de_chegada', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return self.hora_de_partida.strftime("%H:%M") + " - " + self.hora_de_chegada.strftime("%H:%M")

    class Meta:
        
        db_table = 'horario'

class Rota(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    transporteid = models.ForeignKey(Transporte, on_delete = models.CASCADE, db_column='TransporteID')  # Field name made lowercase.
    horarioid = models.ForeignKey(HorarioTransporte, on_delete = models.CASCADE, db_column='HorarioID', blank=True, null=True)  # Field name made lowercase.
    origem = models.CharField(db_column='Origem', max_length=255, blank=True, null=True)  # Field name made lowercase.
    destino = models.CharField(db_column='Destino', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data = models.DateField(db_column='Data', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        
        db_table = 'transporte_universitario_horario'
        

class Rota_Inscricao(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    rotaid = models.ForeignKey(Rota, on_delete= models.CASCADE, db_column='Transporte_Universitario_HorarioID', null=True, blank=True)  # Field name made lowercase.
    inscricaoid = models.ForeignKey("atividades.Inscricao", on_delete= models.CASCADE, db_column='InscricaoID', null=True, blank=True)  # Field name made lowercase.
    num_passageiros = models.IntegerField(db_column='Num_passageiros', blank=True, null=True)

    class Meta:
        
        db_table = 'transporte_universitario_horario_inscricao'



class Ementa(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    dia = models.DateField(db_column='Dia', blank=True, null=True)  # Field name made lowercase.
    #preco_economico = models.FloatField(db_column='Preco_economico_aluno', blank=True, null=True)  # Field name made lowercase.
    #preco_normal = models.FloatField(db_column='Preco_normal_aluno', blank=True, null=True)  # Field name made lowercase.
    #preco_economico_outro = models.FloatField(db_column='Preco_economico_outro', blank=True, null=True)  # Field name made lowercase.
    #preco_outro = models.FloatField(db_column='Preco_outro', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return "Ementa " + str(self.id)

    class Meta:
        db_table = 'ementa'


class Prato(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    ementaid = models.ForeignKey(Ementa, on_delete=models.CASCADE, db_column='EmentaID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.
    tipo = models.CharField(db_column='Tipo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'prato'


class DiaAberto(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='Titulo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.
    contacto = models.IntegerField(db_column='Contacto', blank=True, null=True)  # Field name made lowercase.
    data_inicio = models.DateField(db_column='Data_inicio', blank=True, null=True)  # Field name made lowercase.
    data_fim = models.DateField(db_column='Data_fim', blank=True, null=True)  # Field name made lowercase.
    # limite_de_inscricao_atividades = models.DateField(db_column='Limite_de_inscricao_atividades', blank=True, null=True)  # Field name made lowercase.
    # limite_de_inscricao_participantes = models.DateField(db_column='Limite_de_inscricao_participantes', blank=True, null=True)  # Field name made lowercase.
    data_inicio_inscricao = models.DateField(db_column='Data_inicio_inscricao', blank=True, null=True)
    data_fim_inscricao = models.DateField(db_column='Data_fim_inscricao', blank=True, null=True)
    data_inicio_propor_atividades = models.DateField(db_column='Data_inicio_propor_atividades', blank=True, null=True)
    data_fim_propor_atividades = models.DateField(db_column='Data_fim_propor_atividades', blank=True, null=True)
    preco_aluno= models.FloatField(db_column='Preco_aluno', blank=True, null=True)
    preco_professor= models.FloatField(db_column='Preco_professor', blank=True, null=True)


    class Meta:
        db_table = 'dia_aberto'

tarefas/models.py
from django.db import models

# Create your models here.

class Tarefa(models.Model):
    #id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    sessao_atividadeid_destino = models.ForeignKey("atividades.SessaoAtividade", related_name='destino', on_delete=models.SET_NULL, db_column='Sessao_AtividadeID_Destino', blank=True, null=True)  # Field name made lowercase.
    sessao_atividadeid_origem = models.ForeignKey("atividades.SessaoAtividade", related_name='origem', on_delete=models.SET_NULL, db_column='Sessao_AtividadeID_Origem', blank=True, null=True)  # Field name made lowercase.
    sessao_atividadeid = models.ForeignKey("atividades.SessaoAtividade", related_name='TarefaSessaoAtividade', on_delete=models.CASCADE, db_column='SessaoAtividadeID', blank=True, null=True)
    utilizadorid = models.ForeignKey("utilizadores.Utilizador", related_name='tarefa_coordenador', on_delete=models.DO_NOTHING, db_column='UtilizadorID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    descricao = models.CharField(db_column='Descricao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    tipoTarefa = models.CharField(db_column='TipoTarefa', max_length=255, blank=True, null=True)  # Field name made lowercase.
    origem = models.CharField(db_column='Origem', max_length=255, blank=True, null=True)  # Field name made lowercase.
    destino = models.CharField(db_column='Destino', max_length=255, blank=True, null=True)  # Field name made lowercase.
    horario = models.TimeField(db_column='Horario', blank=True, null=True)  # Field name made lowercase.
    data = models.DateField(db_column='Data', blank=True, null=True)
    estado = models.BooleanField(db_column='Estado', blank=True, null=True)
    colaboradores = models.ManyToManyField("utilizadores.Utilizador", related_name='tarefa_colaborador')

    class Meta:
        db_table = 'tarefa'
        permissions = [
            ("assign_tarefa", "Can assign a tarefa to a colaborador "),
            ("remove_colab_from_tarefa", "Can remove a colaborador from a tarefa"),
        ]


class InscricaoTarefa(models.Model):
    inscricaoid = models.ForeignKey("atividades.Inscricao", on_delete=models.CASCADE, db_column='InscricaoID', blank=True, null=True)
    tarefaid = models.ForeignKey(Tarefa, on_delete=models.CASCADE, db_column='TarefaID', blank=True, null=True)

    class Meta:
        db_table = 'inscricao_tarefa'

diaAbertoConf/templates/diaAbertoConf/Home.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		{% load static %}
		<link rel="icon" href="{% static "diaAbertoConf/logo.png" %}">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static "diaAbertoConf/home.css" %}">
		{% block css %}
		{% endblock %}

        <title>Dia Aberto Ualg</title>
    </head>
    <body>
		<div class="bg-color" id="page-container">

			<div id="content-wrap"> 
        		<nav class="navbar navbar-expand-lg navbar-light bg-white">
        		  	<a href="{% url 'diaAbertoConf:index' %}" class="pr-3"><img src="{% static "diaAbertoConf/logo-navbar.png" %}"></a>
        		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        		    	<span class="navbar-toggler-icon"></span>
        		  	</button>
        		  	<div class="collapse navbar-collapse" id="navbarNav">
					{% block navContent %}
        		    	<ul class="navbar-nav mr-auto">
							{% if user.is_authenticated %}
								{% if perms.atividades.view_inscricao%}
									<li class="nav-item">
        		        				<a class="nav-link" href="#">Inscrições</a>
        		      				</li>
								{% endif %}
								{% if perms.atividades.view_atividade%}
									{% if  perms.atividades.view_edificio and perms.atividades.view_campus and perms.atividades.view_local and perms.atividades.view_unidadeorganica and  perms.atividades.view_departamento and perms.atividades.view_tematica and perms.atividades.view_material and perms.atividades.view_sessaoatividade %}
        		      					<li class="nav-item dropdown">
        									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												Atividades
        									</a>
        									<div class="dropdown-menu" aria-labelledby="navbarDropdown">
          										<a class="dropdown-item" href="{% url 'atividades:allAtividades'%}">Atividades</a>
          										<a class="dropdown-item" href="{% url 'atividades:allEdificios'%}">Edifícios</a>
          										<a class="dropdown-item" href="{% url 'atividades:allCampus'%}">Campus</a>
          										<a class="dropdown-item" href="{% url 'atividades:allLocais'%}">Locais</a>
          										<a class="dropdown-item" href="{% url 'atividades:allUnidadeOrganicas'%}">Unidade Orgânicas</a>
          										<a class="dropdown-item" href="{% url 'atividades:allDepartamentos'%}">Departamentos</a>
          										<a class="dropdown-item" href="{% url 'atividades:allTematicas'%}">Temáticas</a>
          										<a class="dropdown-item" href="{% url 'atividades:allMateriais'%}">Materiais</a>
          										<a class="dropdown-item" href="{% url 'atividades:allSessoes'%}">Horários de Sessões</a>
											</div>
     									</li>
									{%else%}
										<li class="nav-item">
        		        					<a class="nav-link" href="{% url 'atividades:allAtividades' %}">Atividades</a>
        		      					</li>  
									{%endif%}
								{% endif %}
								{% if perms.diaAbertoConf.view_diaaberto%}
									<li class="nav-item">
        		        				<a class="nav-link" href="{% url 'diaAbertoConf:editConfig' %}">Configuração do Dia Aberto</a>
        		      				</li>
								{% endif %}
								{% if perms.diaAbertoConf.view_transporte %}        	      		
        		      				<li class="nav-item dropdown">
        								<a class="nav-link dropdown-toggle" href="#" id="DiaAbertoConfNavbar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          									Transportes
        								</a>
        								<div class="dropdown-menu" aria-labelledby="DiaAbertoConfNavbar">
        									<a class="dropdown-item" href="{% url 'diaAbertoConf:allTransportes'%}">Gestão de Transportes</a>
        								  	<a class="dropdown-item" href="{% url 'diaAbertoConf:allHorarios'%}">Horários de Transportes</a>
        								</div>
      								</li>
								{% endif %}
								{% if perms.diaAbertoConf.view_ementa %}  
        		      				<li class="nav-item">
        		        				<a class="nav-link" href="{% url 'diaAbertoConf:gestaoEmentas'%}">Almoços</a>
        		      				</li>
								{% endif %}
								{% if perms.tarefas.view_tarefa %}
									<li class="nav-item">
        		        				<a class="nav-link" href="{% url 'tarefas:showTarefas' %}">Tarefas</a>
        		      				</li>
								{% endif %}
							{% endif %}
						</ul>
					{% endblock %}
					{% block navButtons %}
						<ul class="navbar-nav">
							{% if user.is_authenticated %}
      						<li class="nav-item dropdown mx-1">
								<button class="btn nav-link" type="button" data-toggle="dropdown">
									<i class="fas fa-bell"></i>
									<span class="badge badge-warning">0</span>

								</button>
								<ul class="dropdown-menu dropdown-menu-right dropdown-width">
      							 	<li><b class="d-flex justify-content-center">Notificações</b></li>
									<li><p class="dropdown-divider"></p></li>
      							 	<li><p class="ml-3 text-muted text-sizing">Não tem Notificações!</p></li>
									<li><p class="dropdown-divider"></p></li>
									<li><a class="ml-3" href="#">Ver todas as notificações</a></li>
      							</ul>
							</li>
							<li class="nav-item dropdown  mx-1">
								<button class="btn nav-link" type="button" data-toggle="dropdown">
									<i class="fas fa-user-circle"></i>	{{user.nome}}					
								</button>
								<ul class="dropdown-menu dropdown-menu-right dropdown-width">
      							 	<li><a class="ml-3 nav-link text-sizing" href="#">Participante Individual</a></li>
									<li><a class="ml-3 nav-link text-sizing" href="#">Professor Secundário</a></li>
									<li><a class="ml-3 nav-link text-sizing" href="#">Colaborador</a></li>
									<li><a class="ml-3 nav-link text-sizing" href="#">Professor Universitário</a></li>
									<li><a class="ml-3 nav-link text-sizing" href="#">Coordenador</a></li>
									<li><a class="ml-3 nav-link text-sizing" href="#">Administrador</a></li>
      							</ul>
							</li>
							<li class="nav-item  mx-1">
								<button class="btn nav-link" type="button" onclick="window.location.href='{% url 'utilizadores:logout' %}'">
									<i class="fas fa-sign-out-alt"></i> Sair
								</button>
							</li>
							{% else %}
							<li class="nav-item  mx-1">
								<button class="btn nav-link" type="button">
									<i class="fas fa-user"></i> Registar-se
								</button>
							</li>
							<li class="nav-item  mx-1">
								<button class="btn nav-link" type="button" onclick="window.location.href='{% url 'utilizadores:login' %}'">
									<i class="fas fa-sign-in-alt"></i> Entrar
								</button>
							</li>
							{% endif %}
        		    	</ul>
					{% endblock %}
        		  	</div>
        		</nav>
				<div class="mt-5 mx-5 px-3 mb-4">
					<div class="card body">	
						{% block content %}
							<div class="row pt-5 mt-3 mb-4 mx-2">
								<div class="col-xs-7 col-sm-7 col-md-7 px-5">
									<h2 class="card-title d-flex justify-content-center">{%if diaAbertoData%}{{diaAbertoData.titulo}}{% else %}Plataforma Dia Aberto{% endif %}</h2>
									<h5 class="card-subtitle mb-4 d-flex justify-content-center">
										{%if diaAbertoData%}
											{% if diaAbertoData.data_fim == diaAbertoData.data_inicio %}
											{{diaAbertoData.data_inicio}}
											{% else %}
											De {{diaAbertoData.data_inicio}} a {{diaAbertoData.data_fim}}
											{% endif %}
										{% else %}
											Simples, Intuitivo, Limpo.
										{% endif %}
									</h5>
									{% if diaAbertoData %}
										<p>{{diaAbertoData.descricao}}</p> 
									{% else %}
										A plataforma online do Dia Aberto foi renovada pelos alunos em âmbito do curso de Licenciatura de Engenharia Informática.
									{% endif %}
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4">
									<img src="{% static "diaAbertoConf/logo-large.png" %}" width="100%" height="100%">
								</div>
							</div>
							<div class="row jumbotron bg-light mx-4">
									<div class="col-xs-7 col-sm-7 col-md-7">
									{% if diaAbertoData %}
										<p>Período de inscricoes de participantes de {{diaAbertoData.data_inicio_inscricao|date:"d/m/Y"}} a {{diaAbertoData.data_fim_inscricao|date:"d/m/Y"}}</p>
										<p>Período de proposta de atividades de  {{diaAbertoData.data_inicio_propor_atividades|date:"d/m/Y"}} a {{diaAbertoData.data_fim_propor_atividades|date:"d/m/Y"}}</p>
										<p>Contacto de suporte: <a href="">{{diaAbertoData.email}}</a> ou <a href="">{{diaAbertoData.contacto}}</a><p>
									{% else %}
										<p>2019 Dia Aberto por Grupo 9</p>
										<p>Contacto de suporte: <a href="">suporte.dia.aberto@ualg.pt</a></p>
									{% endif %}
									</div>
									<div class="col-xs-4 col-sm-4 col-md-4 d-flex justify-content-end">
										<img src="{% static "diaAbertoConf/ualg-logo.png" %}" height="90%" width="90%">
									</div>
							</div>
						{% endblock %}
					</div>
				</div>
			</div>
			<footer id=footer>
				<div class="border-top px-5 py-3 bg-white">
					<div class="row">
						<div class="col-xs-4 col-sm-4 col-md-4 d-flex justify-content-start">
						(c) 2020
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 d-flex justify-content-center">
						Dia Aberto
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 d-flex justify-content-end">
						Designed by Grupo 9
						</div>
					</div>
				</div>
			</footer>
		</div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{% block js %}
		{% endblock %}
	</body>
</html>